name: restro_simplify
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  
  connectivity: ^3.0.6
  shared_preferences: ^2.0.13
  flutter_styled_toast: ^2.1.3
  bottom_navy_bar: ^6.0.0
  provider: ^6.0.2
  wakelock: ^0.6.1+2
  audioplayers: ^1.0.1
  package_info_plus: ^1.4.2
  carousel_slider: ^4.1.1
  desktop_window: ^0.4.0
  

  intl: ^0.17.0
  number_to_words: ^1.0.0
  image: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^1.0.0


flutter:
  
  uses-material-design: true

  
  assets:
    - assets/
    - assets/audio/
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
